### PR TITLE
Add England

### PR DESCRIPTION
**Pull request by stephenkerrhs**
Add England to the list of countries

### CODE REVIEW

**Comment by stephenkerrhs** [comment]
Wrong branch, i need to add the changes to `hst-extra-countries-0-9-3`

**Comment by pusewicz** [comment]
Oh dear! Wrong branches are never good! 🍵

**Comment by dramalho** [comment]
TAN TAN TANNNNNNNNNNN

**Comment by Intrepidd** [comment]
😱 what's up guys ?

**Comment by dramalho** [comment]
REUNION PULL REQUEST!!!!!!!

**Comment by conorhynesire** [comment]
@Intrepidd heyyyyyyyyyyyyy

**Comment by dobrien501** [comment]
getting the gang back together!

**Comment by Intrepidd** [comment]
🍻

**Pull request closed without merging**
